[build-system]
requires = [
    "setuptools>=77.0.3",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[project]
name = "chesstab"
version = "8.1.1.dev0"
authors = [
  { name="Roger Marsh", email="roger.marsh@solentware.co.uk" },
]
description = "Database for chess games."
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment :: Board Games",
    "Intended Audience :: End Users/Desktop",
    "Development Status :: 3 - Alpha",
]
license = "BSD-3-Clause"
license-files = ["LICENCE"]
readme = "README"
dependencies = [
    "solentware-base==5.2.3",
    "solentware-grid==3.0.2",
    "pgn-read==2.5",
    "solentware-misc==1.7.2",
    "uci-net==1.2.8",
]

[project.urls]
Homepage = "http://www.solentware.co.uk"
Repository = "https://github.com/RogerMarsh/chesstab.git"
"Bug Tracker" = "https://github.com/RogerMarsh/chesstab/issues"

[tool.setuptools]
packages = [
    "chesstab",
    "chesstab.basecore",
    "chesstab.core",
    "chesstab.cql",
    "chesstab.gui",
    "chesstab.help_",
    "chesstab.lmdb",
    "chesstab.berkeleydb",
    "chesstab.db",
    "chesstab.db_tkinter",
    "chesstab.dpt",
    "chesstab.sqlite",
    "chesstab.apsw",
    "chesstab.unqlite",
    "chesstab.vedis",
    "chesstab.gnu",
    "chesstab.ndbm",
    "chesstab.fonts",
    "chesstab.tools",
    "chesstab.samples",
    "chesstab.shared",
]

[tool.setuptools.package-data]
chesstab = [
    "help_/*.rst",
    "fonts/*.TTF",
    "fonts/*.zip",
]
